
name: Production
on:
  push:
    branches: [ master ]
  workflow_dispatch:

env: 
  DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Install sequlize-cli
        run: npm install sequelize-cli
      - name: Rollback Migration (if exist)
        run: npx sequelize db:migrate:undo:all --env production
      - name: Migrate DB
        run: npx sequelize db:migrate --env production
      - name: Insert Seeder
        run: npx sequelize db:seed:all --env production
      - name: Create logs
        run: mkdir logs

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PROD }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}